name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master # Desplegar cuando se hace push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH Key File
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USER }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key_path: ~/.ssh/id_rsa
          script: |
            cd /home/alberto/OXYGENLaravel
            git pull origin master
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            sudo systemctl restart apache2